### ISSUE TITLE
The search() function could use improvement.

### ISSUE THREAD

**Issue by schmi710** [caimeng2/UniScraper#4]
The function currently does not actually show where the text specified can be found. As such, we suggest using one of the available methods to cause the searched text to print out in a bright color or with a highlight.

**Comment by bellasaid** [comment]
The return doesn't specify where the text came from and the output might be overwhelming. For example if the text is found in separate paragraphs and the output is both paragraphs one after another, it will be hard to find their locations in the bigger picture of the overall pdf.

**Comment by arnol142** [comment]
Example:

webpage.search("dogs")
For thousands of years, humans bred {dogs} toward the physical and mental traits best suited for the work expected of them. The sleek Greyhound types bred to chase fleet-footed prey, and the huge mastiff types used as guard {dogs} and warriors, are two ancient examples of {dogs} bred for specific jobs.

** Everything in brackets can be highlighted or changed to a different color

**Comment by caimeng2** [comment]
Pull request merged. That's a great suggestion. Thanks.
